### ISSUE TITLE
Following instructions leads to a broken page

### ISSUE THREAD

**Issue by IvoPereira** [cydrickn/sviv#1] opened 2023-02-05 02:09 UTC
Hi there!

I have followed your README instructions, with and without Docker, but both lead to a broken page.

The reason being there are instructions missing for the SSR initialization:

```sh
npm run dev::ssr
```

If done outside of Docker, the env APP_INERTIA_SSR_URL would need to be updated to `http://localhost:13714/render` instead of `http://node:13714/render`.

Besides this, the current SSR server configuration is breaking as well:
![image](https://user-images.githubusercontent.com/1396475/216797817-c27467b7-b3eb-4602-bfac-a20d45dd017b.png)

To solve this, in the `ssr.js` file I replaced the function `resolvePageComponent` with the following, but not sure if it is the best solution:
```js
function resolvePageComponent(name, pages) {
    for (const path in pages) {
        const _name = name || pages[path].default.__name
        if (path.endsWith(`${_name.replace('.', '/')}.vue`)) {
            return typeof pages[path] === 'function'
                ? pages[path]()
                : pages[path]
        }
    }

    throw new Error(`Page not found: ${name}`)
}
```

In the end, I was able to run it.

![image](https://user-images.githubusercontent.com/1396475/216797890-df84b9fb-233c-42b1-a7ed-ab6efd13c18d.png)

However, as you can see, I don't get any styles. So far still researching this one.

Perhaps you have any idea on this @cydrickn?

If I manage to get a totally working setup, I can send a PR (it would be nice to update, since Inertia has received a new update quite recently as well).

**Comment by cydrickn** [comment] 2023-02-09 11:45
Hi, yes i think the solution is correct, maybe you can send a PR.

**Comment by louisdesmet** [comment] 2023-02-16 12:20
After changing what @IvoPereira said, i also come out to the same welcome page without styles, @IvoPereira did u find a fix for this? seems like he is continuously trying to send a request "/build" which fails every second.

**Comment by cydrickn** [comment] 2023-02-20 10:32
Upon investigation the issue is due to the bundle use in this template, where the issue is also fix in the current version of https://github.com/rompetomp/inertia-bundle

You can pull now the current main branch of this to fix the issue, this is the reference of the fix: https://github.com/cydrickn/sviv/commit/12be28562111dcdc2f6531b8d374052611c7a798

**Closed as completed by cydrickn** 2023-02-20 10:32 UTC
